# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

        config.disksize.size = '50GB'

        config.vm.define "arch" do |node|

        # 设置虚拟机的Box
        node.vm.box = "archlinux/archlinux"

        # 设置虚拟机的主机名
        node.vm.hostname="King"

        # 设置虚拟机的IP
        node.vm.network "private_network", ip: "192.168.59.10"

        # 设置主机与虚拟机的共享目录
        node.vm.synced_folder "~/share", "/home/vagrant/share", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=755', 'fmode=644']

        # VirtaulBox相关配置
        node.vm.provider "virtualbox" do |v|
            # 不要图形界面
            v.gui=false

            # 设置虚拟机的名称
            v.name = "King"

            # 设置虚拟机的内存大小  
            v.memory = 512

            # 设置虚拟机的CPU个数
            v.cpus = 1

        end
    end
end
