version: '3'

services:
  dronebot:
    image: drone/drone:1
    ports: ["8080:80", "8443:443"]
    environment:
    - "DRONE_AGENTS_ENABLED=true"
    - "DRONE_GITHUB_SERVER=https://github.com"
    - "DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}"
    - "DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}"
    - "DRONE_RPC_SECRET=${DRONE_RPC_SECRET}"
    - "DRONE_SERVER_HOST=${DRONE_SERVER_HOST}"
    - "DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}"
    restart: always
    env_file:
    - .env
    container_name: dronebot
