Vagrant.configure("2") do |config|

		config.vm.define "concourse" do |node|

		# 设置虚拟机的Box
		node.vm.box = "concourse"

		# 设置虚拟机的主机名
		node.vm.hostname="Ace"

		# 设置虚拟机的IP
		node.vm.network "private_network", ip: "192.168.59.9"

		# 设置主机与虚拟机的共享目录
		node.vm.synced_folder "~/share", "/home/vagrant/share", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=755', 'fmode=644']

		# VirtaulBox相关配置
		node.vm.provider "virtualbox" do |v|
			# 不要图形界面
			v.gui=false

			# 设置虚拟机的名称
			v.name = "concourse"

			# 设置虚拟机的内存大小  
			v.memory = 4096

			# 设置虚拟机的CPU个数
			v.cpus = 2
		# 使用shell脚本进行软件安装和配置
		node.vm.provision "shell", inline: <<-SHELL
			#curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
			#yum makecache
			#yum install -y  vim docker
			#curl -sSL https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
			#chmod +x /usr/local/bin/docker-compose
		SHELL
		end
	end
end
